// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arstaaeqmdnpgooxnyra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyc3RhYWVxbWRucGdvb3hueXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjUzODAsImV4cCI6MjA3MDc0MTM4MH0.ai0OLe3l1qd-9dpFHJDClAGmjFcGjvMdzCzwuzAE6tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});